### ISSUE TITLE
Plugin not on packagist anymore

### ISSUE THREAD

**Issue by olivierbon** [experience/overflow.craft-plugin#4]
The package seems to be [gone from packagist](https://packagist.org/packages/experience/), is this plugin retired?

**Comment by monooso** [comment]
Hi @olivierbon,

I've [updated Packagist](https://packagist.org/packages/experience/overflow).

You may still have problems installing the plugin via Craft, as the Craft Plugin Store points at the old repository. I've contacted Craft support to see if they can help with that. In the meantime you should be able to run `composer require experience/overflow`.

Let me know how you get on.

Cheers,
Stephen

**Comment by monooso** [comment]
@olivierbon The repository link has now been updated [on the plugin store](https://plugins.craftcms.com/overflow), so I think this is all done. Please don't hesitate to open another issue if you run into any problems.
